title: Sample Society
short_title: SampleSoc
# TODO
email: sample@email.com
baseurl: ""
images:
url: "https://samplesoc.github.io"
permalink: pretty
description: This is a generic university society template

destination: docs
collections:
  - events

defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: event
      show_date: "now"
      hide_date: "now"

# Build settings
markdown: kramdown

include: ['_pages']

sass:
    sass_dir: _sass
    
sass:
    style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build

  
# custom variables
cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  bootstrap: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
  bootstrap_hash: "sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
  bootstrap_js: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
  bootstrap_js_hash: "sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
  jquery: "https://code.jquery.com/jquery-3.2.1.min.js"
  jquery_hash: "sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"
  popper: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
  popper_hash: "sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"

  
facebook: "https://www.facebook.com/samplesoc"
